# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:experimental

FROM node:lts-alpine AS base
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Copy source
COPY src ./src

# Default command
CMD ["npm", "start"]
